### PR TITLE
Replace single quotes with double to not speak underscores

### PR DESCRIPTION
**Pull request by seth10**
Thank you for developing this extension! I use it for work to help me stay focused and read code.

This PR is to resolve a minor annoyance when using text-to-speech for code: it enunciating underscores.

Say I have `d['my_dict_key']` in my code. This will be read as "d my underscore dict underscore key". This is hard to understand. I've found that replacing the single quotes with double quotes makes the TTS read it as "d my dict key", much easier to parse aurally.

I propose this PR because some companies' style guide may force users to use single quotes. As for using underscores in names, PEP 8 suggests using underscores rather than camel case (which TTS does read properly already). I'm getting around to making this improvement suggestion as part of Hacktoberfest, could you please add the tag "hacktoberfest-accepted" if you agree?

Thank you for you time in reviewing this, please let me know if you have any feedback.

### CODE REVIEW

**Comment by mattbierner** [comment]
Thanks for looking into this! I think it is ok but just a a few questions:

1. Do you know if this behavior is consistent across operating systems/readers? I see the behavior you describe on MacOS but haven't tested elsewhere
 
2. We probably should have an option to enable/disable this just in case it does cause any issues. Maybe a generic setting that lets you list characters and their substitutions?

**Comment by seth10** [comment]
All set with the generic substitution settings! I tested it on Mac and Windows and the settings work in both. The default of underscore to space makes it so neither platform reads the underscores aloud. I tried another substitution (like "two" to "three") and it also worked on both.

The only oddity is that I can't seem to remove the underscore key from the set of substitutions in the settings. I couldn't find this behavior documented anywhere when using type object and defining a default. However, the user can update it to replace underscore with underscore (instead of space), resulting in no difference.

I'm considering adding a sentence in the description to suggest as such if they don't want this replacement, but I'm not sure if this (not being able to remove the default) is intended behavior in settings ("default" doesn't sound like "required" to me). Another option is to add another new setting, a checkbox to ignore all substitutions, but this feels less elegant to me.

**Comment by mattbierner** [comment]
Thank you! Great work! I'll publish this update shortly

Also added the label `hacktoberfest-accepted` but let me know if it isn't being tracked properly for some reason

**Comment by seth10** [comment]
Thank you very much Matt! Will do. Have a great day and Happy Hacktoberfest 😉 Let me know if you have any other ideas for this project and I'd be happy to help out.

**Pull request merged**
